# Database Modeling & Validate Referential Integrity
-- ---------------------------------------------------------------
ALTER TABLE fact_orders 
MODIFY order_id VARCHAR(50);
ALTER TABLE fact_orders 
ADD CONSTRAINT prm_fact_orders PRIMARY KEY (order_id);
ALTER TABLE DIM_CUSTOMER MODIFY COLUMN CUSTOMER_ID VARCHAR(15);
ALTER TABLE DIM_CUSTOMER ADD CONSTRAINT PRM_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_ID);
ALTER TABLE DIM_DELIVERY_PARTNER MODIFY COLUMN DELIVERY_PARTNER_ID VARCHAR(20);
ALTER TABLE DIM_DELIVERY_PARTNER ADD CONSTRAINT PRM_DIM_DELIVERY_PARTNER PRIMARY KEY (DELIVERY_PARTNER_ID);
ALTER TABLE DIM_MENU_ITEM MODIFY COLUMN MENU_ITEM_ID VARCHAR(20);
ALTER TABLE DIM_MENU_ITEM ADD CONSTRAINT PRM_MENU_ITEM PRIMARY KEY (MENU_ITEM_ID);
ALTER TABLE DIM_RESTAURANT MODIFY COLUMN RESTAURANT_ID VARCHAR(15);
ALTER TABLE DIM_RESTAURANT ADD CONSTRAINT PRM_DIM_RESTAURANT PRIMARY KEY (RESTAURANT_ID);

-- Assigning foreign keys 
ALTER TABLE FACT_ORDERS MODIFY COLUMN CUSTOMER_ID VARCHAR(20);
# CANT MAKE FOREIGN KEY BCZ CUSTOMER_ID IN ORDERS NOT FOUND IN DIM_CUSTOMER
ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_FACTORDERS_CUSTOMER_ID foreign key(CUSTOMER_ID) references DIM_CUSTOMER(CUSTOMER_ID);
# Checking if any order delivered for unkown customers
SELECT *
FROM fact_orders fo
LEFT JOIN dim_customer dc
ON fo.customer_id = dc.customer_id
WHERE dc.customer_id IS NULL and lower(fo.is_cancelled)='y';

# checking if any unknown delivery_id in orders
select fo.delivery_partner_id from fact_orders fo left join dim_delivery_partner dp on fo.delivery_partner_id = dp.delivery_partner_id where dp.delivery_partner_id is null;

# check for duplicate customer signup
select customer_id,count(*) from dim_customer group by customer_id having count(*)>1;

ALTER TABLE FACT_ORDERS MODIFY COLUMN RESTAURANT_ID VARCHAR(20);
ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_DIM_RESTUARANT foreign key(RESTAURANT_ID) references DIM_RESTAURANT(RESTAURANT_ID);
ALTER TABLE FACT_ORDERS MODIFY COLUMN DELIVERY_PARTNER_ID VARCHAR(20);
# CANT MAKE FOREIGN KEY BCZ DELIVERY_PARTNER_ID IN ORDERS NOT FOUND IN DIM_DELIVERY_PARTNERS
ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_DELIVERY_PARTNER_ID foreign key(DELIVERY_PARTNER_ID) references DIM_RESTAURANT(RESTAURANT_ID);
ALTER TABLE DIM_MENU_ITEM MODIFY COLUMN RESTAURANT_ID VARCHAR(20);
ALTER TABLE DIM_MENU_ITEM ADD CONSTRAINT FK_RESTAURANT_ID foreign key(RESTAURANT_ID) references DIM_RESTAURANT(RESTAURANT_ID);
ALTER TABLE FACT_DELIVERY_PERFORMANCE MODIFY COLUMN ORDER_ID VARCHAR(50);
ALTER TABLE FACT_DELIVERY_PERFORMANCE ADD CONSTRAINT FK_FDP_UNIQUE UNIQUE(ORDER_ID);
ALTER TABLE FACT_DELIVERY_PERFORMANCE ADD CONSTRAINT FK_ORDER__ID foreign key(ORDER_ID) references FACT_ORDERS(ORDER_ID);
ALTER TABLE FACT_ORDER_ITEMS MODIFY COLUMN ORDER_ID VARCHAR(50);
-- order_id not found in parent table fact_orders
ALTER TABLE FACT_ORDER_ITEMS ADD CONSTRAINT FK_OT_ORDER_ID foreign key(ORDER_ID) REFERENCES FACT_ORDERS(ORDER_ID);

-- Removed order item records with no matching ORDER_ID in FACT_ORDERS.
DELETE FOI FROM FACT_ORDER_ITEMS FOI LEFT JOIN FACT_ORDERS FO ON FOI.ORDER_ID = FO.ORDER_ID WHERE FO.ORDER_ID IS NULL;
-- Assigning foregin key
ALTER TABLE FACT_ORDER_ITEMS ADD CONSTRAINT FK_OT_ORDER_ID foreign key(ORDER_ID) REFERENCES FACT_ORDERS(ORDER_ID);

-- Assinging foregin key
ALTER TABLE FACT_ORDER_ITEMS MODIFY COLUMN MENU_ITEM_ID VARCHAR(50);
ALTER TABLE FACT_ORDER_ITEMS ADD CONSTRAINT FK_FOI_MENU_ITEM_ID foreign key(MENU_ITEM_ID) REFERENCES DIM_MENU_ITEM(MENU_ITEM_ID);

-- Assigning foreign key
ALTER TABLE FACT_RATINGS MODIFY COLUMN ORDER_ID VARCHAR(50);	
ALTER TABLE FACT_RATINGS ADD CONSTRAINT FK_FR_UNIQUE UNIQUE (ORDER_ID);
ALTER TABLE FACT_RATINGS ADD CONSTRAINT FK_FR__ORDER_ID foreign key(ORDER_ID) REFERENCES FACT_ORDERS(ORDER_ID);

-- Assigning foreign key
ALTER TABLE FACT_RATINGS MODIFY COLUMN CUSTOMER_ID VARCHAR(50);
ALTER TABLE FACT_RATINGS ADD CONSTRAINT FK_FR_CUSTOMER_ID foreign key(CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID);
ALTER TABLE FACT_RATINGS MODIFY COLUMN RESTAURANT_ID VARCHAR(50);
ALTER TABLE FACT_RATINGS ADD CONSTRAINT FK_FR_RESTAURANT_ID foreign key(RESTAURANT_ID) REFERENCES DIM_RESTAURANT(RESTAURANT_ID);

# Indentifing No. of Customers which are not in the dim_customer table 
SELECT COUNT(distinct fo.customer_id) as 'Total Unkown Customers'
FROM fact_orders fo
LEFT JOIN dim_customer dc
ON fo.customer_id = dc.customer_id
WHERE dc.customer_id IS NULL;

# Total unkown customer enteries in order table
SELECT COUNT(fo.customer_id) as 'Unkown Customer Enteries'
FROM fact_orders fo
LEFT JOIN dim_customer dc
ON fo.customer_id = dc.customer_id
WHERE dc.customer_id IS NULL;

# Removing fake or incorrect orders where unknown-customers found in orders
delete fo from fact_orders fo left join dim_customer dc on fo.customer_id = dc.customer_id where dc.customer_id is null;
set sql_safe_updates = 0;

# checking fake orders data in fact_delivery performance
select * from fact_delivery_performance fdp inner join fact_orders fo on fdp.order_id = fo.order_id left join dim_customer dc on fo.customer_id = dc.customer_id where dc.customer_id is null;

# Counting total_Count
select * from fact_delivery_performance fdp inner join fact_orders fo on fdp.order_id = fo.order_id left join dim_customer dc on fo.customer_id = dc.customer_id where dc.customer_id is null;

# Remove this incorrect records from fact_delivery_performance
delete fdp from fact_delivery_performance fdp inner join fact_orders fo on fdp.order_id = fo.order_id left join dim_customer dc on fo.customer_id = dc.customer_id where dc.customer_id is null;

# FIXED : CANT MAKE FOREIGN KEY BCZ DELIVERY_PARTNER_ID IN ORDERS NOT FOUND IN DIM_DELIVERY_PARTNERS
ALTER TABLE FACT_ORDERS ADD CONSTRAINT FK_FACTORDERS_CUSTOMER_ID foreign key(CUSTOMER_ID) references DIM_CUSTOMER(CUSTOMER_ID);

# CANT MAKE FOREIGN KEY BCZ DELIVERY_PARTNER_ID IN ORDERS NOT FOUND IN DIM_DELIVERY_PARTNERS
SELECT DC.CRISIS_STAGE ,COUNT(*) AS 'CANCELLED ORDERS' FROM FACT_ORDERS FO LEFT JOIN DIM_DELIVERY_PARTNER DP ON FO.DELIVERY_PARTNER_ID = DP.DELIVERY_PARTNER_ID  LEFT JOIN DIM_CUSTOMER DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID  WHERE FO.IS_CANCELLED = 'Y' AND DP.DELIVERY_PARTNER_ID IS NULL AND DC.CUSTOMER_ID IS NOT NULL GROUP BY DC.CRISIS_STAGE ORDER BY COUNT(*) DESC;
SELECT DC.CRISIS_STAGE ,COUNT(*) AS 'CANCELLED ORDERS' FROM FACT_ORDERS FO LEFT JOIN DIM_DELIVERY_PARTNER DP ON FO.DELIVERY_PARTNER_ID = DP.DELIVERY_PARTNER_ID  LEFT JOIN DIM_CUSTOMER DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID  WHERE FO.IS_CANCELLED = 'Y' AND DP.DELIVERY_PARTNER_ID IS NOT NULL AND DC.CUSTOMER_ID IS NOT NULL GROUP BY DC.CRISIS_STAGE ORDER BY COUNT(*) DESC;

# Cancelled Orders with Missing Delivery Partner Records
SELECT DC.CRISIS_STAGE,
SUM(CASE WHEN DP.DELIVERY_PARTNER_ID IS NULL THEN 1 ELSE 0 END) AS cancelled_without_partner,
SUM(CASE WHEN DP.DELIVERY_PARTNER_ID IS NOT NULL THEN 1 ELSE 0 END) AS cancelled_with_partner,
SUM(CASE WHEN DP.DELIVERY_PARTNER_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN DP.DELIVERY_PARTNER_ID IS NOT NULL THEN 1 ELSE 0 END),0) AS ratio,
CONCAT(ROUND(SUM(CASE WHEN DP.DELIVERY_PARTNER_ID IS NULL THEN 1 ELSE 0 END)*100/NULLIF(COUNT(*),0),2),"%") AS percentage
FROM FACT_ORDERS FO
LEFT JOIN DIM_DELIVERY_PARTNER DP ON FO.DELIVERY_PARTNER_ID = DP.DELIVERY_PARTNER_ID
LEFT JOIN DIM_CUSTOMER DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
WHERE FO.IS_CANCELLED = 'Y' AND DC.CUSTOMER_ID IS NOT NULL
GROUP BY DC.CRISIS_STAGE;

# CHECKING IF DELIVERY_ID IN ORDER TABLE NOT EXISTS IN DELIVERY_PARTNER RECORDS
SELECT COUNT(*) FROM FACT_ORDERS FO LEFT JOIN DIM_DELIVERY_PARTNER DP ON FO.DELIVERY_PARTNER_ID = DP.DELIVERY_PARTNER_ID WHERE FO.DELIVERY_PARTNER_ID IS NOT NULL AND DP.DELIVERY_PARTNER_ID IS NULL;

# How many cancelled orders had no delivery partner ASSIGNED?
SELECT DC.CRISIS_STAGE as 'Signup Crisis Stage',
SUM(CASE WHEN FO.DELIVERY_PARTNER_ID IS NULL THEN 1 ELSE 0 END) AS cancelled_without_partner,
SUM(CASE WHEN FO.DELIVERY_PARTNER_ID IS NOT NULL THEN 1 ELSE 0 END) AS cancelled_with_partner,
SUM(CASE WHEN FO.DELIVERY_PARTNER_ID IS NULL THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN FO.DELIVERY_PARTNER_ID IS NOT NULL THEN 1 ELSE 0 END),0) AS ratio,
CONCAT(ROUND(SUM(CASE WHEN FO.DELIVERY_PARTNER_ID IS NULL THEN 1 ELSE 0 END)*100/NULLIF(COUNT(*),0),2),"%") AS percentage
FROM FACT_ORDERS FO
LEFT JOIN DIM_DELIVERY_PARTNER DP ON FO.DELIVERY_PARTNER_ID = DP.DELIVERY_PARTNER_ID
LEFT JOIN DIM_CUSTOMER DC ON FO.CUSTOMER_ID = DC.CUSTOMER_ID
WHERE FO.IS_CANCELLED = 'Y' AND DC.CUSTOMER_ID IS NOT NULL
GROUP BY DC.CRISIS_STAGE;

# Delete delivery performance records for cancelled orders that never had a delivery partner assigned.
SELECT * FROM FACT_DELIVERY_PERFORMANCE DP INNER JOIN FACT_ORDERS FO ON DP.ORDER_ID = FO.ORDER_ID LEFT JOIN DIM_DELIVERY_PARTNER DDP ON FO.DELIVERY_PARTNER_ID = DDP.DELIVERY_PARTNER_ID WHERE FO.IS_CANCELLED = "Y" AND DDP.DELIVERY_PARTNER_ID IS NULL;
DELETE DP FROM FACT_DELIVERY_PERFORMANCE DP INNER JOIN FACT_ORDERS FO ON DP.ORDER_ID = FO.ORDER_ID LEFT JOIN DIM_DELIVERY_PARTNER DDP ON FO.DELIVERY_PARTNER_ID = DDP.DELIVERY_PARTNER_ID WHERE DDP.DELIVERY_PARTNER_ID IS NULL;


-- TABLE NAME RENAMING
ALTER TABLE DIM_CUSTOMER RENAME TO CUSTOMER;
ALTER TABLE DIM_DELIVERY_PARTNER RENAME TO DELIVERY_PARTNER;
ALTER TABLE DIM_MENU_ITEM RENAME TO MENU_ITEM;
ALTER TABLE DIM_RESTAURANT RENAME TO RESTAURANT;
ALTER TABLE FACT_DELIVERY_PERFORMANCE RENAME TO DELIVERY_PERFORMANCE;
ALTER TABLE FACT_ORDER_ITEMS RENAME TO ORDER_ITEMS;
ALTER TABLE FACT_ORDERS RENAME TO ORDERS;
ALTER TABLE FACT_RATINGS RENAME TO RATINGS;


# Customer segmentation (Pre-Crisis,Crisis,Post-Crisis)
set sql_safe_updates = 0;
alter table dim_customer 
add column crisis_stage varchar(20);
update dim_customer
set crisis_stage=
case when signup_date <'2025-06-01' then 'Pre Crisis'
# since our date start from nov-2024
when signup_date >= '2025-06-01' and signup_date < '2025-07-01' then 'Crisis'
/* other we can use date_format more precious will be date_truncate
select count(*) from dim_customer where date_format(signup_date,'%Y-%m') ='2025-06';*/
when signup_date >='2025-07-01' then 'Recovery'
else 'Unkownn'
end;
set sql_safe_updates = 1;


# Number of New Customer across stages?
select crisis_stage as 'Crisis Stage',count(*) as 'Total Signup' from dim_customer group by crisis_stage;
